# Documentation à propos de cette page : https://fshschool.org/docs/sushi/configuration/

id: ans.fhir.fr.eclaire
canonical: https://interop.esante.gouv.fr/ig/fhir/eclaire # the last part of canonical and id must be the same
name: ECLAIRE
title: ECLAIRE(Essais CLiniques Accessibles Interconnectés pour la Recherche ouverts à l'Ecosystème)
description: Implementation Guide pour définir l'API FHIR pour ECLAIRE (Essais CLiniques Accessibles Interconnectés pour la Recherche ouverts à l'Ecosystème)
publisher: 
  name: ANS
  url: https://esante.gouv.fr
dependencies:
  ans.annuaire.fhir.r4: 0.2.0
  hl7.fhir.fr.core: 1.1.0
status: draft
version: 0.1.0 # shall conforms to Semantic Versioning https://fr.wiktionary.org/wiki/SemVer
fhirVersion: 4.0.1
copyrightYear: 2020+
releaseLabel: trial-use

parameters:
    shownav: 'true'



pages:
    index.md:
        title: Accueil
    specifications_techniques.md:
        st_flux1.md:
            title: Extraction de données des essais cliniques
    mapping.md:
        title: Mapping FHIR
    search_param.md:
        title: Critères de recherche
    modifiers.md:
        title: Paramètres et modificateurs de requêtes FHIR
    autres_ressources.md:
        title: Autres Ressources
        securite.md:
            title: Sécurité
        downloads.md:
            title: Téléchargements et usages   
    about.md:
        title: A propos de ce guide

menu:
    Accueil: index.html
    Description des flux:
        Extraction de données des essais cliniques: st_flux1.html
    Mapping FHIR: mapping.html
    Critères de recherche: search_param.html
    Paramètres et modificateurs de requêtes FHIR: modifiers.html
    Ressources de conformité: artifacts.html
    Autres ressources:
        Sécurité: securite.html
        Téléchargements et usage: downloads.html
        "Spécifications FHIR ": new-tab {{site.data.fhir.path}}index.html
        "Site de l'ANS ": new-tab https://esante.gouv.fr/
    A propos de ce guide: about.html